//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GraphLabs.DomainModel
{
    using System;
    using GraphLabs.DomainModel.Infrastructure;
    
    public enum ExecutionStatus : byte
    {
        Interrupted = 2,
        Complete = 1,
        Executing = 0
    }
}
