//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GraphLabs.DomainModel
{
    using System;
    using System.Collections.Generic;
    using GraphLabs.DomainModel.Infrastructure;
    
    
    #pragma warning disable 1591
    
    public partial class Group : AbstractEntity
    {
        protected Group()
        {
            this.Students = new HashSet<Student>();
            this.LabWorks = new HashSet<LabWork>();
        }
    
        public long Id { get; private set; }
        public bool IsOpen { get; set; }
        public int FirstYear { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Student> Students { get; set; }
        public virtual ICollection<LabWork> LabWorks { get; set; }
    }
    
    #pragma warning restore 1591
    
}
