//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GraphLabs.DomainModel
{
    using System;
    using System.Collections.Generic;
    using GraphLabs.DomainModel.Infrastructure;
    
    
    #pragma warning disable 1591
    
    public abstract partial class AbstractLabSchedule : AbstractEntity
    {
        protected AbstractLabSchedule()
        {
        }
    
        public long Id { get; set; }
        public System.DateTime DateFrom { get; set; }
        public System.DateTime DateTill { get; set; }
        public LabExecutionMode Mode { get; set; }
    
        public virtual LabWork LabWork { get; set; }
    }
    
    #pragma warning restore 1591
    
}
