//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GraphLabs.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Action
    {
        public long Id { get; private set; }
        public string Description { get; set; }
        public int Penalty { get; set; }
        public System.DateTime Time { get; set; }
    
        public virtual Result Result { get; set; }
        public virtual Task Task { get; set; }
    }
}
