//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GraphLabs.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    
    #pragma warning disable 1591
    
    public partial class AnswerVariant
    {
        public long Id { get; private set; }
        public string Answer { get; set; }
        public bool IsCorrect { get; set; }
    
        public virtual TestQuestion TestQuestion { get; set; }
    }
    
    #pragma warning restore 1591
    
}
