//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GraphLabs.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnswerVariant
    {
        public long Id { get; private set; }
        public string Answer { get; set; }
        public bool IsCorrect { get; set; }
    
        public virtual TestQuestion TestQuestion { get; set; }
    }
}
