//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GraphLabs.DomainModel
{
    using System;
    using System.Collections.Generic;
    using GraphLabs.DomainModel.Infrastructure;
    
    
    #pragma warning disable 1591
    
    public partial class Category : AbstractEntity
    {
        protected Category()
        {
            this.SubCategories = new HashSet<SubCategory>();
        }
    
        public long Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<SubCategory> SubCategories { get; set; }
    }
    
    #pragma warning restore 1591
    
}
