//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GraphLabs.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Group
    {
        public Group()
        {
            this.Students = new HashSet<Student>();
            this.LabWorks = new HashSet<LabWork>();
        }
    
        public long Id { get; private set; }
        public int Number { get; set; }
        public bool IsOpen { get; set; }
        public int FirstYear { get; set; }
    
        public virtual ICollection<Student> Students { get; set; }
        public virtual ICollection<LabWork> LabWorks { get; set; }
    }
}
