//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GraphLabs.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Group
    {
        public Group()
        {
            this.Students = new HashSet<Student>();
            this.LabWorks = new HashSet<LabWork>();
        }
    
        public long Id { get; private set; }
        public int Number { get; set; }
        public bool IsOpen { get; set; }
        public int FirstYear { get; set; }
    
        public virtual ICollection<Student> Students { get; set; }
        public virtual ICollection<LabWork> LabWorks { get; set; }
    }
}
