//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GraphLabs.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class LabVariant
    {
        public LabVariant()
        {
            this.TestQuestions = new HashSet<TestQuestion>();
            this.TaskVariants = new HashSet<TaskVariant>();
            this.Results = new HashSet<Result>();
        }
    
        public long Id { get; private set; }
        public string Number { get; set; }
        public long Version { get; set; }
    
        public virtual ICollection<TestQuestion> TestQuestions { get; set; }
        public virtual ICollection<TaskVariant> TaskVariants { get; set; }
        public virtual LabWork LabWork { get; set; }
        public virtual ICollection<Result> Results { get; set; }
    }
}
