//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GraphLabs.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    
    #pragma warning disable 1591
    
    public partial class LabWork
    {
        public LabWork()
        {
            this.LabVariants = new HashSet<LabVariant>();
            this.LabEntries = new HashSet<LabEntry>();
            this.Groups = new HashSet<Group>();
        }
    
        public long Id { get; private set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> AcquaintanceFrom { get; set; }
        public Nullable<System.DateTime> AcquaintanceTill { get; set; }
    
        public virtual ICollection<LabVariant> LabVariants { get; set; }
        public virtual ICollection<LabEntry> LabEntries { get; set; }
        public virtual ICollection<Group> Groups { get; set; }
    }
    
    #pragma warning restore 1591
    
}
