//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GraphLabs.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class News
    {
        public long Id { get; private set; }
        public string Text { get; set; }
        public System.DateTime PublicationTime { get; set; }
        public string Title { get; set; }
        public Nullable<System.DateTime> LastModificationTime { get; set; }
    
        public virtual User User { get; set; }
    }
}
