//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GraphLabs.DomainModel
{
    using System;
    using System.Collections.Generic;
    using GraphLabs.DomainModel.Infrastructure;
    
    
    #pragma warning disable 1591
    
    public partial class News : AbstractEntity
    {
        protected News()
        {
        }
    
        public long Id { get; private set; }
        public string Text { get; set; }
        public System.DateTime PublicationTime { get; private set; }
        public string Title { get; set; }
        public Nullable<System.DateTime> LastModificationTime { get; private set; }
    
        public virtual User User { get; set; }
    }
    
    #pragma warning restore 1591
    
}
