//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GraphLabs.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Session
    {
        public System.DateTime CreationTime { get; set; }
        public System.DateTime LastAction { get; set; }
        public System.Guid Guid { get; private set; }
        public string IP { get; set; }
    
        public virtual User User { get; set; }
    }
}
