//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GraphLabs.DomainModel
{
    using System;
    using System.Collections.Generic;
    using GraphLabs.DomainModel.Infrastructure;
    
    
    #pragma warning disable 1591
    
    public partial class Session : AbstractEntity
    {
        protected Session()
        {
        }
    
        public System.DateTime CreationTime { get; set; }
        public System.DateTime LastAction { get; set; }
        public System.Guid Guid { get; set; }
        public string IP { get; set; }
    
        public virtual User User { get; set; }
    }
    
    #pragma warning restore 1591
    
}
