//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GraphLabs.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student : User
    {
        public Student()
        {
            this.Results = new HashSet<Result>();
        }
    
        public bool IsVerified { get; set; }
        public bool IsDismissed { get; set; }
    
        public virtual Group Group { get; set; }
        public virtual ICollection<Result> Results { get; set; }
    }
}
