//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GraphLabs.DomainModel
{
    using System;
    using System.Collections.Generic;
    using GraphLabs.DomainModel.Infrastructure;
    
    
    #pragma warning disable 1591
    
    public partial class Task : AbstractEntity
    {
        protected Task()
        {
            this.TaskVariants = new HashSet<TaskVariant>();
        }
    
        public long Id { get; private set; }
        public string Name { get; set; }
        public byte[] VariantGenerator { get; set; }
        public string Sections { get; set; }
        public string Version { get; set; }
        public string Note { get; set; }
    
        public virtual ICollection<TaskVariant> TaskVariants { get; set; }
        public virtual TaskData TaskData { get; set; }
    }
    
    #pragma warning restore 1591
    
}
