//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GraphLabs.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestQuestion
    {
        public TestQuestion()
        {
            this.LabVariant = new HashSet<LabVariant>();
        }
    
        public long Id { get; private set; }
        public string Question { get; set; }
    
        public virtual ICollection<LabVariant> LabVariant { get; set; }
        public virtual Category Category { get; set; }
    }
}
