//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GraphLabs.DomainModel
{
    using System;
    using System.Collections.Generic;
    using GraphLabs.DomainModel.Infrastructure;
    
    
    #pragma warning disable 1591
    
    public partial class TestPool : AbstractEntity
    {
        protected TestPool()
        {
            this.LabVariants = new HashSet<LabVariant>();
            this.PoolScores = new HashSet<PoolScore>();
        }
    
        public int Id { get; set; }
        public string Strategy { get; set; }
        public string Forfeit { get; set; }
    
        public virtual ICollection<LabVariant> LabVariants { get; set; }
        public virtual ICollection<PoolScore> PoolScores { get; set; }
    }
    
    #pragma warning restore 1591
    
}
