//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GraphLabs.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestQuestion
    {
        public TestQuestion()
        {
            this.AnswerVariants = new HashSet<AnswerVariant>();
            this.LabVariant = new HashSet<LabVariant>();
        }
    
        public long Id { get; private set; }
        public string Description { get; set; }
        public string Value { get; set; }
        public string TypeOfQuestion { get; set; }
        public string Section { get; set; }
    
        public virtual ICollection<AnswerVariant> AnswerVariants { get; set; }
        public virtual ICollection<LabVariant> LabVariant { get; set; }
    }
}
