//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GraphLabs.DomainModel
{
    using System;
    using System.Collections.Generic;
    using GraphLabs.DomainModel.Infrastructure;
    
    
    #pragma warning disable 1591
    
    public partial class User : AbstractEntity
    {
        protected User()
        {
            this.News = new HashSet<News>();
            this.Sessions = new HashSet<Session>();
        }
    
        public long Id { get; private set; }
        public string Surname { get; set; }
        public string Name { get; set; }
        public string FatherName { get; set; }
        public string PasswordHash { get; set; }
        public string Email { get; set; }
        public UserRole Role { get; set; }
    
        public virtual ICollection<News> News { get; set; }
        public virtual ICollection<Session> Sessions { get; set; }
    }
    
    #pragma warning restore 1591
    
}
