//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GraphLabs.DomainModel {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ValidationErrors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationErrors() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GraphLabs.DomainModel.ValidationErrors", typeof(ValidationErrors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата &quot;с&quot; должна быть больше даты &quot;по&quot;..
        /// </summary>
        internal static string AbstractLabSchedule_OnEntityValidating_Дата_с_должна_быть_больше_даты_по {
            get {
                return ResourceManager.GetString("AbstractLabSchedule_OnEntityValidating_Дата_с_должна_быть_больше_даты_по", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Необходимо указать описание действия..
        /// </summary>
        internal static string Action_OnEntityValidating_Необходимо_указать_описание_действия_ {
            get {
                return ResourceManager.GetString("Action_OnEntityValidating_Необходимо_указать_описание_действия_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Штрафной балл может находиться только в диапазоне от 0 до 100..
        /// </summary>
        internal static string Action_OnEntityValidating_Штрафной_балл_может_находиться_только_в_диапазоне_от_0_до_100_ {
            get {
                return ResourceManager.GetString("Action_OnEntityValidating_Штрафной_балл_может_находиться_только_в_диапазоне_от_0_" +
                        "до_100_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Необработанная ошибка обновления базы данных.
        /// </summary>
        internal static string DB_Update_Неизвестная_ошибка_ {
            get {
                return ResourceManager.GetString("DB_Update_Неизвестная_ошибка_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Существуют сущности, связанные с данной.
        /// </summary>
        internal static string DB_Update_Существуют_FK_ {
            get {
                return ResourceManager.GetString("DB_Update_Существуют_FK_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка валидации: {0}.
        /// </summary>
        internal static string GraphLabsValidationException_Ошибка_валидации_0 {
            get {
                return ResourceManager.GetString("GraphLabsValidationException_Ошибка_валидации_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка валидации значения [{0}]. {1}.
        /// </summary>
        internal static string GraphLabsValidationException_Ошибка_валидации_значения_0_1 {
            get {
                return ResourceManager.GetString("GraphLabsValidationException_Ошибка_валидации_значения_0_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Необходимо указать непустое название группы..
        /// </summary>
        internal static string Group_OnEntityValidating_Необходимо_указать_непустое_название_группы {
            get {
                return ResourceManager.GetString("Group_OnEntityValidating_Необходимо_указать_непустое_название_группы", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Версия варианта должна быть больше 0..
        /// </summary>
        internal static string LabVariant_OnEntityValidating_Версия_варианта_должна_быть_больше_0_ {
            get {
                return ResourceManager.GetString("LabVariant_OnEntityValidating_Версия_варианта_должна_быть_больше_0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Номер варианта не может быть пустым..
        /// </summary>
        internal static string LabVariant_OnEntityValidating_Номер_варианта_не_может_быть_пустым_ {
            get {
                return ResourceManager.GetString("LabVariant_OnEntityValidating_Номер_варианта_не_может_быть_пустым_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Название лабораторной работы не может быть пустым..
        /// </summary>
        internal static string LabWork_OnValidating_Название_лабораторной_работы_не_может_быть_пустым_ {
            get {
                return ResourceManager.GetString("LabWork_OnValidating_Название_лабораторной_работы_не_может_быть_пустым_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Указан некорректный период ознакомления (дата окончания должна быть строго больше даты начала)..
        /// </summary>
        internal static string LabWork_OnValidating_Указан_некорректный_период_ознакомления_ {
            get {
                return ResourceManager.GetString("LabWork_OnValidating_Указан_некорректный_период_ознакомления_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Заголовок новости не может быть пустым..
        /// </summary>
        internal static string News_OnValidating_Заголовок_новости_не_может_быть_пустым_ {
            get {
                return ResourceManager.GetString("News_OnValidating_Заголовок_новости_не_может_быть_пустым_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Текст новости не может быть пустым..
        /// </summary>
        internal static string News_OnValidating_Текст_новости_не_может_быть_пустым_ {
            get {
                return ResourceManager.GetString("News_OnValidating_Текст_новости_не_может_быть_пустым_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на IP-адрес имеет неверный формат..
        /// </summary>
        internal static string Session_OnValidating_IP_адрес_имеет_неверный_формат_ {
            get {
                return ResourceManager.GetString("Session_OnValidating_IP_адрес_имеет_неверный_формат_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Должна быть указана контрольная сумма..
        /// </summary>
        internal static string Session_OnValidating_Должна_быть_указана_контрольная_сумма_ {
            get {
                return ResourceManager.GetString("Session_OnValidating_Должна_быть_указана_контрольная_сумма_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Момент последнего действия не может находиться раньше момента создания сессии..
        /// </summary>
        internal static string Session_OnValidating_Момент_последнего_действия_не_может_находиться_раньше_момента_создания_сессии_ {
            get {
                return ResourceManager.GetString("Session_OnValidating_Момент_последнего_действия_не_может_находиться_раньше_момент" +
                        "а_создания_сессии_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нельзя менять значение IP-адреса..
        /// </summary>
        internal static string Session_OnValidating_Нельзя_менять_значение_IP_адреса_ {
            get {
                return ResourceManager.GetString("Session_OnValidating_Нельзя_менять_значение_IP_адреса_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Новое значение системного времени не может быть меньше старого..
        /// </summary>
        internal static string Settings_OnValidating_Новое_значение_системного_времени_не_может_быть_меньше_старого_ {
            get {
                return ResourceManager.GetString("Settings_OnValidating_Новое_значение_системного_времени_не_может_быть_меньше_стар" +
                        "ого_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Необходимо указать версию..
        /// </summary>
        internal static string Task_OnValidating_Необходимо_указать_версию_ {
            get {
                return ResourceManager.GetString("Task_OnValidating_Необходимо_указать_версию_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Необходимо указать название задания..
        /// </summary>
        internal static string Task_OnValidating_Необходимо_указать_название_задания_ {
            get {
                return ResourceManager.GetString("Task_OnValidating_Необходимо_указать_название_задания_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Указан пустой исполняемый файл задания..
        /// </summary>
        internal static string Task_OnValidating_Указан_пустой_исполняемый_файл_задания_ {
            get {
                return ResourceManager.GetString("Task_OnValidating_Указан_пустой_исполняемый_файл_задания_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Версия должна быть больше 0..
        /// </summary>
        internal static string TaskVariant_OnValidating_Версия_должна_быть_больше_0_ {
            get {
                return ResourceManager.GetString("TaskVariant_OnValidating_Версия_должна_быть_больше_0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Должны быть указаны данные варианта..
        /// </summary>
        internal static string TaskVariant_OnValidating_Должны_быть_указаны_данные_варианта_ {
            get {
                return ResourceManager.GetString("TaskVariant_OnValidating_Должны_быть_указаны_данные_варианта_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Необходимо указать версию генератора варианта..
        /// </summary>
        internal static string TaskVariant_OnValidating_Необходимо_указать_версию_генератора_варианта_ {
            get {
                return ResourceManager.GetString("TaskVariant_OnValidating_Необходимо_указать_версию_генератора_варианта_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Необходимо указать номер варианта..
        /// </summary>
        internal static string TaskVariant_OnValidating_Необходимо_указать_номер_варианта_ {
            get {
                return ResourceManager.GetString("TaskVariant_OnValidating_Необходимо_указать_номер_варианта_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Должно быть указано значение HashSalt..
        /// </summary>
        internal static string User_OnValidating_Должно_быть_указано_значение_HashSalt_ {
            get {
                return ResourceManager.GetString("User_OnValidating_Должно_быть_указано_значение_HashSalt_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Должно быть указано значение PasswordHash..
        /// </summary>
        internal static string User_OnValidating_Должно_быть_указано_значение_PasswordHash_ {
            get {
                return ResourceManager.GetString("User_OnValidating_Должно_быть_указано_значение_PasswordHash_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Необходимо указать имя пользователя..
        /// </summary>
        internal static string User_OnValidating_Необходимо_указать_имя_пользователя_ {
            get {
                return ResourceManager.GetString("User_OnValidating_Необходимо_указать_имя_пользователя_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Необходимо указать фамилию пользователя..
        /// </summary>
        internal static string User_OnValidating_Необходимо_указать_фамилию_пользователя_ {
            get {
                return ResourceManager.GetString("User_OnValidating_Необходимо_указать_фамилию_пользователя_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Указан неверный Email-адрес..
        /// </summary>
        internal static string User_OnValidating_Указан_неверный_Email_адрес_ {
            get {
                return ResourceManager.GetString("User_OnValidating_Указан_неверный_Email_адрес_", resourceCulture);
            }
        }

        public static string AbstractLabStartpage_OnEntityValidating_Дата_с_должна_быть_больше_даты_по { get; internal set; }
    }
}
