//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GraphLabs.Site {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UserMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UserMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GraphLabs.Site.UserMessages", typeof(UserMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Недостаточно прав для просмотра запрошенной страницы. Если Вы уверены, что права должны быть, обратитесь к системному администратору..
        /// </summary>
        internal static string ACCES_DENIED {
            get {
                return ResourceManager.GetString("ACCES_DENIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы сможете войти, когда преподаватель подтвердит вашу учётную запись, о чём будет сообщено дополнительно по e-mail..
        /// </summary>
        internal static string AccountController_Register_Вы_сможете_войти_когда_преподаватель_подтвердит_вашу_учётную_запись_о_чём_будет_сообщено_дополнительно_по_e_mail {
            get {
                return ResourceManager.GetString("AccountController_Register_Вы_сможете_войти_когда_преподаватель_подтвердит_вашу_у" +
                        "чётную_запись_о_чём_будет_сообщено_дополнительно_по_e_mail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Для выполнения запрошенного действия необходимо выполнить вход в систему..
        /// </summary>
        internal static string AUTH_REQUIRED {
            get {
                return ResourceManager.GetString("AUTH_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to При регистрации возникла ошибка. Вероятно, пользователь с таким e-mail уже существует..
        /// </summary>
        internal static string DUPLICATE_LOGIN {
            get {
                return ResourceManager.GetString("DUPLICATE_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменения сохранены..
        /// </summary>
        internal static string EDIT_COMPLETE {
            get {
                return ResourceManager.GetString("EDIT_COMPLETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новость успешно опубликована..
        /// </summary>
        internal static string HomeController_Edit_Новость_успешно_опубликована_ {
            get {
                return ResourceManager.GetString("HomeController_Edit_Новость_успешно_опубликована_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Старый пароль введён неверно. Пожалуйста, попробуйте снова..
        /// </summary>
        internal static string ILLEGAL_PASSWORD {
            get {
                return ResourceManager.GetString("ILLEGAL_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось найти указанную комбинацию e-mail и пароля..
        /// </summary>
        internal static string LOGIN_PASSWORD_NOT_FOUND {
            get {
                return ResourceManager.GetString("LOGIN_PASSWORD_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль успешно изменён..
        /// </summary>
        internal static string PASSWORD_CHANGED {
            get {
                return ResourceManager.GetString("PASSWORD_CHANGED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистрация успешно выполнена..
        /// </summary>
        internal static string REGISTRATION_COMPLETE {
            get {
                return ResourceManager.GetString("REGISTRATION_COMPLETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузка не удалась. Задание с таким названием и версией уже существует..
        /// </summary>
        internal static string TASK_EXISTS {
            get {
                return ResourceManager.GetString("TASK_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось загрузить указанный файл. Вероятно, он имеет неверный формат..
        /// </summary>
        internal static string UPLOAD_ERROR {
            get {
                return ResourceManager.GetString("UPLOAD_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Файл для загрузки не указан..
        /// </summary>
        internal static string UPLOAD_FILE_NOT_SPECIFIED {
            get {
                return ResourceManager.GetString("UPLOAD_FILE_NOT_SPECIFIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вариант с полученным Id не найден..
        /// </summary>
        internal static string Вариант_с_полученным_Id_не_найден_ {
            get {
                return ResourceManager.GetString("Вариант_с_полученным_Id_не_найден_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Задание с полученным Id не найдено..
        /// </summary>
        internal static string Задание_с_полученным_Id_не_найдено_ {
            get {
                return ResourceManager.GetString("Задание_с_полученным_Id_не_найдено_", resourceCulture);
            }
        }
    }
}
