//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GraphLabs.DomainModel
{
    using System;
    using GraphLabs.DomainModel.Infrastructure;
    
    public enum ScoringStrategy : int
    {
        AllCorrectVariantsShouldBeSpecified = 0,
        AnyCorrectVariantCanBeSpecified = 1
    }
}
