//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GraphLabs.DomainModel
{
    using System;
    using System.Collections.Generic;
    using GraphLabs.DomainModel.Infrastructure;
    
    
    #pragma warning disable 1591
    
    public partial class AbstractResultEntry : AbstractEntity
    {
        protected AbstractResultEntry()
        {
        }
    
        public long Id { get; set; }
        public ExecutionStatus Status { get; set; }
        public int Score { get; set; }
    
        public virtual Result Result { get; set; }
    }
    
    #pragma warning restore 1591
    
}
