//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GraphLabs.DomainModel.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Settings
    {
        public long Id { get; private set; }
        public System.DateTime SystemDate { get; set; }
        public byte[] DefaultVariantGenerator { get; set; }
    }
}
