//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GraphLabs.DomainModel
{
    using System;
    using System.Collections.Generic;
    using GraphLabs.DomainModel.Infrastructure;
    
    
    #pragma warning disable 1591
    
    public partial class Group : AbstractEntity
    {
        protected Group()
        {
            this.Students = new HashSet<Student>();
            this.LabWorks = new HashSet<LabWork>();
        }
    
        public long Id { get; private set; }
        public bool IsOpen { get; set; }
        public int FirstYear { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Student> Students { get; set; }
        public virtual ICollection<LabWork> LabWorks { get; set; }
    }
    
    #pragma warning restore 1591
    
}
